[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]


[build]
target = "x86-rustos.json"
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
json-target-spec = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"